create table public.place_search_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null check (action in ('autocomplete', 'details', 'nearby')),
  created_at timestamptz not null default now()
);

create index place_search_requests_user_created_idx
  on public.place_search_requests (user_id, created_at desc);

alter table public.place_search_requests enable row level security;

revoke all on table public.place_search_requests from anon, authenticated;
grant all on table public.place_search_requests to service_role;
grant usage, select on sequence public.place_search_requests_id_seq to service_role;

comment on table public.place_search_requests is
  'Server-only request ledger used to cap paid Google Places traffic per signed-in user.';
